"""availability table and relation to book

Revision ID: 67ca9aaec5a6
Revises: 10d0c7344b22
Create Date: 2023-03-22 09:28:01.745376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ca9aaec5a6'
down_revision = '10d0c7344b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('date_borrow', sa.String(length=10), nullable=True),
    sa.Column('date_return', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    # ### end Alembic commands ###
